"""Host command implementation over an injected synchronous read32/write32 transport.

The adapter is intentionally platform-owned: no AXI, USB or live board access is claimed.
The register transaction transcript generated by this API can drive RTL simulations.
"""
import struct
import time
import numpy as np
from . import registers as r


class Controller:
    def __init__(self, read32, write32, timeout_s=5):
        self.read32=read32;self.write32=write32;self.timeout_s=timeout_s

    def wait(self, predicate):
        deadline=time.monotonic()+self.timeout_s
        while time.monotonic()<deadline:
            status=self.read32(r.STATUS)
            if status&32:
                self.abort();raise RuntimeError(f'Digital fault 0x{self.read32(r.ERROR):x}')
            if predicate(status):return status
        self.abort();raise TimeoutError('Digital operation timed out; disabled')

    def abort(self):self.write32(r.CONTROL,4)

    def configure(self, config, frequency=None, first_tx=64, count=128):
        self.abort()
        self.wait(lambda s: bool(s&128))  # drain an outstanding conversion
        values={r.FREQUENCY:config['carrier_hz'] if frequency is None else frequency,
                r.BURST_CYCLES:config['burst_cycles'],r.START_PHASE:round(config['start_phase_rad']*256/(2*np.pi))%256,
                r.FIRST_TX:first_tx,r.SCAN_COUNT:count,r.SAMPLE_PERIOD:config['clock_hz']//config['adc']['sample_rate_hz'],
                r.PRE_SAMPLES:config['pretrigger_samples'],r.MAIN_SAMPLES:config['main_samples'],
                r.TAIL_SAMPLES:config['ringdown_samples'],r.SETTLE_CYCLES:config['settle_cycles'],r.GUARD_CYCLES:config['guard_cycles']}
        for address,value in values.items():self.write32(address,int(value))
        return values

    def start(self, mode=r.MODE_CALIBRATE_GEOMETRY):
        if mode not in (r.MODE_CALIBRATE_GEOMETRY,r.MODE_CHARACTERIZE_TX,r.MODE_CALIBRATE_PHASE):
            raise ValueError('Use a calibration mode')
        self.write32(r.MODE,mode);self.write32(r.CONTROL,3)

    def read_capture(self):
        self.wait(lambda s:bool(s&8))
        n=self.read32(r.FRAME_COUNT)
        if not 0<n<=1024:self.abort();raise ValueError('Invalid capture size')
        def stamp(lo,hi):return self.read32(lo)|(self.read32(hi)<<32)
        meta={'tx':self.read32(r.CAPTURE_TX),'sequence':self.read32(r.CAPTURE_SEQ),
              'first_sample_tick':stamp(r.TIMESTAMP_LO,r.TIMESTAMP_HI),
              'burst_tick':stamp(r.BURST_TIMESTAMP_LO,r.BURST_TIMESTAMP_HI),
              'tx_enable_tick':stamp(r.TX_ENABLE_TIMESTAMP_LO,r.TX_ENABLE_TIMESTAMP_HI),
              'sample_period_ticks':self.read32(r.SAMPLE_PERIOD),
              'frequency_hz':self.read32(r.FREQUENCY),'frame_count':n}
        data=bytearray()
        for address in range(n*4):
            self.write32(r.BUFFER_ADDR,address);data.extend(struct.pack('<I',self.read32(r.BUFFER_DATA)))
        return np.frombuffer(data,dtype='<i2').reshape(n,8).copy(),meta

    def acknowledge(self):self.write32(r.ACK_CAPTURE,1)

    def apply_map(self, rows, mode=r.MODE_NORMAL_FIELD):
        if mode not in (r.MODE_NORMAL_FIELD,r.MODE_VALIDATE_FIELD):raise ValueError('Invalid field mode')
        if len(rows)!=128 or sorted(x['channel'] for x in rows)!=list(range(128)):raise ValueError('Complete unique map required')
        for x in rows:
            if not 0<=x['requested_phase']<256 or not 0<=x['calibration_phase']<256:raise ValueError('Invalid phase code')
        self.abort()
        for x in rows:
            self.write32(r.MAP_CHANNEL,x['channel'])
            self.write32(r.MAP_DATA,(bool(x['enabled'])<<16)|(x['calibration_phase']<<8)|x['requested_phase'])
            self.write32(r.MAP_WRITE,1)
        self.write32(r.MAP_COMMIT,1)
        self.wait(lambda s:not(self.read32(r.MAP_STATUS)&2) and bool(s&64))
        self.write32(r.MODE,mode);self.write32(r.CONTROL,1)
