`timescale 1ns/1ps
// Host/model-to-core integration uses files generated by Python, not TB phase formulas.
module tb_phase_map;
    reg clk=0; always #15.151515 clk=~clk;
    reg rst_n=0,write_valid=0,commit=0,channel_enable=0;
    reg [6:0] write_channel=0;
    reg [7:0] requested_phase=0,calibration_phase=0;
    wire [127:0] waveform;
    wire commit_ack;
    reg [16:0] map[0:127];
    reg [127:0] expected[0:824];
    sono_core dut(.clk(clk),.rst_n(rst_n),.write_valid(write_valid),.commit(commit),
        .channel_enable(channel_enable),.write_channel(write_channel),.requested_phase(requested_phase),
        .calibration_phase(calibration_phase),.waveform(waveform),.commit_ack(commit_ack),
        .write_ready(),.pending(),.command_error(),.active_valid(),.master_phase(),
        .effective_phase(),.sample_valid(),.period_boundary());
    initial begin
        $readmemh("phase_map.hex",map); $readmemh("phase_waveform.hex",expected);
        repeat(4) @(negedge clk); rst_n=1;
        for(integer c=0;c<128;c=c+1) begin
            @(negedge clk); write_valid=1;write_channel=c;
            {channel_enable,calibration_phase,requested_phase}=map[c];
        end
        @(negedge clk);write_valid=0;
        @(negedge clk);commit=1;
        @(negedge clk);commit=0;
        wait(commit_ack); #2;
        if(waveform!==expected[0]) $fatal(1,"map integration at commit");
        for(integer cycle=1;cycle<825;cycle=cycle+1) begin
            @(posedge clk);#2;
            if(waveform!==expected[cycle]) $fatal(1,"Python field map waveform mismatch cycle=%0d",cycle);
        end
        $display("PASS model phase map -> core -> 128 waveform bits, 825 cycles"); $finish;
    end
    initial begin #100000; $fatal(1,"timeout"); end
endmodule
