/* Generated by scripts/generate_transport.py. */
#ifndef SF_GENERATED_H
#define SF_GENERATED_H
#define SF_MAGIC "SFP2"
#define SF_VERSION 1u
#define SF_MAX_PAYLOAD 256u
#define SF_WATCHDOG_MS 1000u
#define SF_CMD_PING 1u
#define SF_CMD_GET_VERSION 2u
#define SF_CMD_GET_CAPABILITIES 3u
#define SF_CMD_GET_STATUS 4u
#define SF_CMD_SAFE_DISABLE 5u
#define SF_CMD_READ_REGISTER 6u
#define SF_CMD_WRITE_REGISTER 7u
#define SF_CMD_BEGIN_MAP 16u
#define SF_CMD_MAP_CHUNK 17u
#define SF_CMD_COMMIT_MAP 18u
#define SF_CMD_GET_MAP_STATUS 19u
#define SF_ERR_OK 0u
#define SF_ERR_BAD_FRAME 1u
#define SF_ERR_BAD_SEQUENCE 2u
#define SF_ERR_NOT_CONNECTED 3u
#define SF_ERR_UNSUPPORTED 4u
#define SF_ERR_DENIED 5u
#define SF_ERR_BUS_ERROR 6u
#define SF_CAP_BASIC 1u
#define SF_CAP_MAP 2u
#define SF_REG_CONTROL 0u
#define SF_REG_STATUS 4u
#define SF_REG_MODE 8u
#define SF_REG_FREQUENCY 12u
#define SF_REG_BURST_CYCLES 16u
#define SF_REG_START_PHASE 20u
#define SF_REG_FIRST_TX 24u
#define SF_REG_SCAN_COUNT 28u
#define SF_REG_SAMPLE_PERIOD 32u
#define SF_REG_PRE_SAMPLES 36u
#define SF_REG_MAIN_SAMPLES 40u
#define SF_REG_TAIL_SAMPLES 44u
#define SF_REG_SETTLE_CYCLES 48u
#define SF_REG_GUARD_CYCLES 52u
#define SF_REG_BUFFER_ADDR 56u
#define SF_REG_BUFFER_DATA 60u
#define SF_REG_FRAME_COUNT 64u
#define SF_REG_CAPTURE_TX 68u
#define SF_REG_CAPTURE_SEQ 72u
#define SF_REG_TIMESTAMP_LO 76u
#define SF_REG_TIMESTAMP_HI 80u
#define SF_REG_MAP_CHANNEL 84u
#define SF_REG_MAP_DATA 88u
#define SF_REG_MAP_WRITE 92u
#define SF_REG_MAP_COMMIT 96u
#define SF_REG_MAP_STATUS 100u
#define SF_REG_ERROR 104u
#define SF_REG_ACK_CAPTURE 108u
#define SF_REG_BURST_TIMESTAMP_LO 112u
#define SF_REG_BURST_TIMESTAMP_HI 116u
#define SF_REG_TX_ENABLE_TIMESTAMP_LO 120u
#define SF_REG_TX_ENABLE_TIMESTAMP_HI 124u
static inline int sf_valid_register(unsigned a) {
 switch(a) {
 case 0u:
 case 4u:
 case 8u:
 case 12u:
 case 16u:
 case 20u:
 case 24u:
 case 28u:
 case 32u:
 case 36u:
 case 40u:
 case 44u:
 case 48u:
 case 52u:
 case 56u:
 case 60u:
 case 64u:
 case 68u:
 case 72u:
 case 76u:
 case 80u:
 case 84u:
 case 88u:
 case 92u:
 case 96u:
 case 100u:
 case 104u:
 case 108u:
 case 112u:
 case 116u:
 case 120u:
 case 124u:
 return 1; default: return 0;
 }
}
#endif
