"""Generate RTL/Python register definitions and board-independent ADC/channel constants."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]


def outputs():
    c=json.loads((ROOT/'config/system_baseline.json').read_text());r=json.loads((ROOT/'config/register_map.json').read_text())
    sv='// Generated by scripts/generate_system.py. Do not edit.\n'
    py='# Generated by scripts/generate_system.py. Do not edit.\n'
    md='# Register map\n\n'+r['bus']+'\n\n| Name | Byte address |\n|---|---|\n'
    for name,addr in r['registers'].items():
        sv+=f'localparam [7:0] REG_{name}=8\'h{addr:02x};\n';py+=f'{name} = {addr}\n';md+=f'| {name} | 0x{addr:02x} |\n'
    for name,value in r['modes'].items():sv+=f'localparam [2:0] MODE_{name}=3\'d{value};\n';py+=f'MODE_{name} = {value}\n'
    defaults={'CLOCK_HZ':c['clock_hz'],'ADC_PERIOD':c['clock_hz']//c['adc']['sample_rate_hz'],
              'BUFFER_DEPTH':c['buffer_depth'],'CARRIER_HZ':c['carrier_hz'],'BURST_CYCLES':c['burst_cycles'],
              'PRE_SAMPLES':c['pretrigger_samples'],'MAIN_SAMPLES':c['main_samples'],'TAIL_SAMPLES':c['ringdown_samples'],
              'SETTLE_CYCLES':c['settle_cycles'],'GUARD_CYCLES':c['guard_cycles']}
    for name,value in defaults.items():sv+=f'localparam integer SYS_{name}={value};\n'
    return {'rtl/generated/registers.svh':sv,'software/control/registers.py':py,'docs/architecture/REGISTER_MAP.md':md}


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    for name,body in outputs().items():
        path=ROOT/name
        if a.check:
            if not path.exists() or path.read_text()!=body:raise SystemExit('Stale generated file: '+name)
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(body,encoding='utf-8',newline='\n')
    print('Generated configuration check PASS' if a.check else 'Generated register definitions')
