"""Write current-stage candidate contracts from observed evidence. No release assertions."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'evidence/pre_pcb_board_ready'
DOC=ROOT/'docs/hardware'

def write(name,text):
    p=DOC/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')

def main():
    prefix='# SonoField-FPGA v2 / pre-PCB interface review\n\nCurrent model: GPT-6.1 Sol High. Status: CANDIDATE / NOT ELECTRICALLY FROZEN.\n\n'
    def table(config):
        a=json.loads((ROOT/'config'/config).read_text())
        t='| Connector pin | Package ball | Bank | Signal | Direction |\n|---|---|---|---|---|\n'
        for r in a['pins']:t+=f"| {r['connector_pin']} | {r['fpga_package_pin']} | {r['package_properties']['bank']} | {r['signal']} | {r['direction']} |\n"
        return t
    write('J3_J4_DATA_INTERFACE.md',prefix+'''J3 carries upper TX00..63 via serializer lanes00..15; J4 carries lower TX00..63 via lanes16..31. Each lane sends local channel3,2,1,0. This is the logical shift order; the physical 595 QA/QB/QC/QD wiring still requires netlist verification. A four-used-output 595 uses eight hardware stages; no claim of final QA mapping is made here. Both arrays share deterministic timing, with separate board enables required at integration.\n\nPins9/12 are AUX5V and unused for array/AFE/ADC power. Pins10/11 are ground. FPGA package legality is verified; actual bank34/35 VCCO, connector orientation/continuity and electrical timing are not.\n\n'''+table('j3_upper_data_interface.json')+'\n'+table('j4_lower_data_interface.json'))
    text=prefix+'''The existing architecture has ONE AD7606B for eight RX paths, four from each array. There is ONE ADC SPI bus, not two opposing ADC buses. Candidate J5 uses five upper TX/blanking controls, ten shared ADC signals and one proposed fault input (16/16). J6 uses five lower TX/blanking controls plus one proposed fault input (6/16), leaving ten unassigned pins. Lower analog RX reaches the shared ADC through its analog interconnect; it does not duplicate digital ADC ownership on J6.\n\nUPPER/LOWER_FAULT_N are proposals requiring firmware/RTL/electrical implementation. Current core exports a global safety disable, not separately qualified per-array enables. The upper/lower controls must derive from the same timing reference and each board must remain disabled during reset, loss of lock, transport failure and absent external power. Exact assignments are provisional, not an accepted PCB freeze.\n\nJ5 spans banks34 AND35. J6 uses bank34. All5V pins are AUX/UNUSED, never a GPIO voltage specification.\n\n'''+table('j5_upper_control_adc_interface.json')+'\n'+table('j6_lower_control_adc_interface.json')
    write('J5_J6_SIGNAL_BUDGET.md',text)
    write('J5_J6_CONTROL_ADC_INTERFACE.md',text)
    write('SERIALIZER_THROUGHPUT_PROOF.md',prefix+'''Actual RTL lifecycle: accepted start at cycle0; four high/low shift pairs at cycles1..8; latch high at9; completion and busy release at10; next accepted start at11. Icarus and Vivado XSim each executed100 consecutive starts spaced11 cycles, four shift edges per frame and done offset10, with no overrun. Evidence: pre_pcb_board_ready/throughput/0..4.log and cross_simulator_checks.json.\n\nMaximum phase refresh demand =41500×256=10,624,000 updates/s. Minimum core frequency =11×10,624,000=116,864,000Hz. At nominal132MHz the frame capacity is12,000,000/s; slack to demanded capacity is1,376,000/s (12.95% of demand). At33.333MHz input and a3.96 ratio, candidate core131,998,680Hz has capacity11,999,880/s and still meets throughput. Final board clock remains NOT FROZEN pending routed timing and verified clock integration. Throughput does not validate off-chip setup/hold.\n\nADC clock is independently derived: adc_serial uses a modulo-four divider, therefore nominal33MHz at132MHz core, not66MHz. TX shift clock nominal66MHz only during serialization.\n''')
    write('FPGA_TO_PCB_TIMING_BUDGET.md',prefix+'''TX: one core cycle (~7.576ns at132MHz) separates data launch from shift-clock rising; one cycle separates final shift rising from latch rising. Budget must include FPGA tCO(min/max), package/pin skew, board routing, level translator and clock-only buffer delays,595 SER setup/hold and SRCLK-to-RCLK setup, loading, jitter and PVT. Clock-only buffering can improve setup while worsening hold; never use typical delays to certify either.\n\nReceiver setup margin = available launch/capture interval + clock_path_min - data_path_max - required_setup - uncertainty. Hold margin = data_change_min - clock_capture_max - required_hold - uncertainty, using the relevant NEXT data-change edge. Values not measured or constrained remain UNKNOWN, not zero. No input/output delays, IOSTANDARD or unconstrained-path exclusions have been fabricated.\n\nAD7606B: Rev B table5 specifies60MHz maximum SCLK at VDRIVE>=2.7V (40MHz below2.7V), DOUT access delay up to15ns (25ns below2.7V). Existing RTL SCLK=core/4≈33MHz and samples old DOUT at a subsequent rising launch; the nominal30.303ns cycle must cover maximum ADC output delay plus outgoing/incoming path delays and FPGA input setup. This frequency check alone cannot qualify capture timing.\n\nSources: [AD7606B Rev B](https://www.analog.com/media/en/technical-documentation/data-sheets/ad7606b.pdf), [SN74LVC595A](https://www.ti.com/lit/ds/symlink/sn74lvc595a.pdf), [SN74LVC244A](https://www.ti.com/product/SN74LVC244A/part-details/SN74LVC244APWR). Receiver voltage and exact routed loads remain unknown. No final positive margin asserted.\n''')
    write('MANUAL_VCCO_MEASUREMENT_REQUIRED.md',prefix+'''Measure actual VCCO for bank34 and bank35 on this board revision against ground, using a manufacturer-identified rail/test point. Do not probe arbitrary package balls or infer VCCO from connector5V. Record board revision, point identifier, voltage, instrument, photo and date. J3/J6/N18 use bank34; J4 uses bank35; J5 spans both. Compare proposed translator VCCA and ADC VDRIVE to measured bank voltages before choosing LVCMOS18/25/33 or emitting XDC. Disable outputs and leave external PCB disconnected until the match is verified. A schematic with identified bank supply nets may replace exploratory measurement for documenting the intended voltage, but does not replace electrical qualification.\n''')
    (OUT/'clock').mkdir(exist_ok=True)
    (OUT/'clock/clock_facts.json').write_text(json.dumps({'documented_input_pin':'N18','input_hz':33333000,
      'classification':'USER_APPROVED_DOCUMENT_FALLBACK_NOT_MEASURED','historical_input_hz':33000000,
      'precedence':'20261003 formal contract and Excel supersede old const priority',
      'candidate_mmcm':{'divclk':2,'feedback_multiplier':49.5,'clkout0_divide':6.25,'vco_hz':824991750,'core_hz':131998680},
      'mmcm_candidate':'ARITHMETIC_ONLY_NOT_INTEGRATED_OR_VENDOR_VALIDATED','final_board_clock':'NOT_FROZEN',
      'pl_oscillator_measured':False,'ps_reference_clock_hz':None},indent=2)+'\n')
    (OUT/'MISSING_PHYSICAL_FACTS.md').write_text('''# Exact missing facts after automatic inspection\n\nCurrent model: GPT-6.1 Sol High. No physical step below has been performed.\n\n| Fact | Why it blocks | Sources searched | Required evidence/action |\n|---|---|---|---|\n| Bank34/35 VCCO | IO standards and translator voltages cannot be frozen | All Zynq7020 files, current Excel/image, package database, previous board audit | Revision-matched schematic naming the rails, or identified test-point measurements as specified in MANUAL_VCCO_MEASUREMENT_REQUIRED.md |\n| FT2232-B TX/RX to PS UART instance/MIO | COM4 is enumerated but no verified PS path exists | USB descriptors, board pin tables/const/images, firmware platform profile | Manufacturer UART schematic, or unpowered continuity test of identified FTDI TX/RX to documented PS MIO pads; record instance and MIO pair |\n| PS input reference clock, reset source and board preset | Safe PS initialization/XSA/BSP cannot be inferred from PL N18 | Board sources, installed Vivado/Vitis, generic PS7 templates | Correct board preset or schematic/clock values; generic Zed/zc702 ps7_init is not a Robei preset |\n| Connector pin1 orientation and real continuity | Excel resolves documentation but actual PCB routing is not measured | New Excel/image and legal package pin query | Board-revision matched connector drawing or unpowered continuity verification of intended signal pins |\n| TX/ADC link delay and loading | Off-chip setup/hold cannot be accepted from OOC timing | Existing BOM/native schematic and official part datasheets | Approved component/voltage/load/cable budget plus min/max timing constraints; later scope evidence on actual prototype |\n\nN18 nominal33.333MHz is an explicitly approved fallback, so physical oscillator measurement is not reintroduced as a blocking requirement. No need to reread full chip ordering code: XC7Z020-1CLG400C is already USER_CONFIRMED_PHYSICAL_FACT.\n\nSeparate development prerequisites: install/locate a valid ARM Cortex-A9 baremetal target compiler/BSP; construct verified PS/AXI clock/reset platform; implement and test separate array-disable integration; obtain post-route timing closure and then run the real transport tests. These are engineering work, not claimed missing physical measurements.\n''',encoding='utf-8')
    print('WROTE candidate interfaces, throughput proof, electrical budget and exact missing facts')

if __name__=='__main__':main()
