"""Generate C/Python transport constants from protocol and existing register map."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def outputs():
    spec=json.loads((ROOT/'config/transport_protocol.json').read_text())
    regs=json.loads((ROOT/'config/register_map.json').read_text())['registers']
    values={'VERSION':spec['version'],'MAX_PAYLOAD':spec['max_payload'],'WATCHDOG_MS':spec['watchdog_ms']}
    for group,prefix in [('commands','CMD_'),('status','ERR_'),('capabilities','CAP_')]:
        values.update({prefix+k:v for k,v in spec[group].items()})
    py='# Generated by scripts/generate_transport.py.\nMAGIC = '+repr(spec['magic'].encode())+'\n'
    c='/* Generated by scripts/generate_transport.py. */\n#ifndef SF_GENERATED_H\n#define SF_GENERATED_H\n'
    c+='#define SF_MAGIC "'+spec['magic']+'"\n'
    for name,val in values.items():py+=f'{name} = {val}\n';c+=f'#define SF_{name} {val}u\n'
    for name,val in regs.items():c+=f'#define SF_REG_{name} {val}u\n'
    c+='static inline int sf_valid_register(unsigned a) {\n switch(a) {\n'
    for val in regs.values():c+=f' case {val}u:\n'
    c+=' return 1; default: return 0;\n }\n}\n#endif\n'
    sv='// Generated from config/register_map.json.\nfunction automatic sf_valid_address(input [31:0] address);\n case(address)\n'
    sv+=','.join(f"32'h{x:08x}" for x in regs.values())+':sf_valid_address=1;\n default:sf_valid_address=0;\n endcase\nendfunction\n'
    return {'software/board/generated.py':py,'firmware/ps_service/generated.h':c,'rtl/generated/transport_valid.svh':sv}

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    for name,body in outputs().items():
        path=ROOT/name
        if a.check:
            if not path.exists() or path.read_text()!=body:raise SystemExit('Stale '+name)
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(body,encoding='utf-8',newline='\n')
    print('Transport constants PASS')
